### ISSUE TITLE
Config File to be able to exclude npm modules from updating its version

### ISSUE THREAD

**Issue by turkelinda** [rse/upd#1]
upd is really a great tool! 
and it is great that the versions can be updated automatically (= enter 'upd' in the command line) . But sometimes there are modules you exactly want a concrete version, and you do not want this version to be updated. But all the Versions of the other modules should still be updated automatically. 
Of course, you can handle this in the command line, but then you always have to remember which versions should be updated and which not. So it would be nice to write it down in a config file, then u can always do the complete update (= enter 'upd' in the command line) and do not have to worry about versions, that should not be updated.
And another benefit of that config file would be, that you can comment, why exacly the choosen version is used.

Thanks ;)

**Comment by rse** [comment]
There is an "upd" section possible in the package.json to exclude modules since a longer time, so we can now close this issue, of course.
