### ISSUE TITLE
new dependency package-json does not support proxies

### ISSUE THREAD

**Issue by JochenHoertreiter** [rse/upd#3]
Using upd 2.x.x is not working behind a proxy due to package-json not supporting this setup.
The recommended fix there was to update "got" to support proxies out of the box.
https://github.com/sindresorhus/package-json/issues/43
directing to
https://github.com/sindresorhus/package-json/issues/22

**Comment by rse** [comment]
So, no chance to use `package-json` at all? Or do I miss a point? Do we have to replace `package-json` by a own variant? I'm confused. Can `package-json` now be forced to work behind a proxy or not?!

**Comment by rse** [comment]
OK, UPD 2.1.0 now has support for proxies through a local variant of the `package-json` functionality.
