### ISSUE TITLE
Version upd 2.7.8 is false targeted for node version >=10.0.0

### ISSUE THREAD

**Issue by JochenHoertreiter** [rse/upd#4]
Since the update of yargs to ^17 
upd is only working on node >=12
since yargs is targeted for that node version

using upd on node < 12 causes an error in yargs stating that node >=12 is required

last upd version running on node below 12 is 2.7.7

**Comment by rse** [comment]
As Node 10 is already end of life, bumping up the dependency to Node >= 12 is just fine for me. I'll update UPD accordingly. Thanks, Jochen.

**Comment by rse** [comment]
Now fixed with UPD 2.7.9
